### ISSUE TITLE
Don't show onboarding pager to user if they have seen it in the past

### ISSUE THREAD

**Issue by aakash1313** [covidsafe/App-Android#19]
PR is created for the issue. If they have already scrolled through the pager, we should not make them scroll again, instead take them to permissions fragment directly.

**Comment by justinklchan** [comment]
The onboarding page is only shown once. I think you may have cloned a version of the code where a configuration was set to force the onboarding page to be shown all the time for debugging purposes.

Look at OnboardingActivity.java
We store a boolean state indicating whether the user has gone through the onboarding steps:
boolean b = prefs.getBoolean(getString(R.string.onboard_enabled_pkey),true);

If the user has done this, then it won't be shown.

In MainActivity.java this is set to false:
editor.putBoolean(getString(R.string.onboard_enabled_pkey), false);

Most likely in the version you cloned the "forceOnboard" variable in OnboardingActivity.java was enabled.

**Comment by aakash1313** [comment]
I saw that part in the code, what i am referring to not showing the pager
again if they have seen it in the past. We can discuss tomorrow. Opening
the issues. You will get to know from the changes i made. :)

Thanks and Regards,
Akashdeep Singh

**Comment by aakash1313** [comment]
I am working on the latest code 👍
