### ISSUE TITLE
App layout is broken on BLU A4 2019

### ISSUE THREAD

**Issue by kumpera** [covidsafe/App-Android#30]
![75A1B205-DC8A-41C5-B42D-285C7AA5CC7B_1_105_c](https://user-images.githubusercontent.com/5738/80042402-e184e800-84cc-11ea-91a7-022a37a94814.jpeg)

**Comment by aakash1313** [comment]
Hey @kumpera , hopefully the linked PR will solve your issue , plus improve the  UI rendering performance.  I tested on the 240*320 resolution. Attached the screenshot for reference 
![shot](https://user-images.githubusercontent.com/3194646/80079490-35abbe80-8505-11ea-9b6d-a8754aa6ca84.PNG)

**Comment by kumpera** [comment]
Amazing! I don't have Android dev setup on my laptop so I can't easily test your fix. I'll do it if you upload an apk somewhere I can try.
