### ISSUE TITLE
Is there a way to manually log contacts?

### ISSUE THREAD

**Issue by tlringer** [covidsafe/App-Android#34]
Hi, I installed the Android demo application today. Great work. I am really excited about this. I am very very happy with the communication of permission use especially. The button for broadcasting is very nicely designed and makes it clear when my information is being broadcasted.

I am just wondering if there is a way to manually log known contacts in addition to the broadcasted information. I couldn't see a way to do this. It could be useful while adoption of contact tracing applications is still relatively low, and to have a nice centralized location for that information for manual contact tracing efforts if I or someone I know gets sick later.

**Comment by justinklchan** [comment]
@tlringer Thanks so much for your interest in this! There is indeed a way to do this! Although it is a bit buried right now.
If you go to Health report > Diagnosis there is a panel where you prepare for a contact tracer interview. 
Within those list of steps is a location to add contacts.

But given this feedback, we'll also make sure to allow adding of contacts in the Contact log tab, which is what we had considered doing previously also.

**Comment by justinklchan** [comment]
resolved in latest commit
