### ISSUE TITLE
Should the DEBUG flag be on?

### ISSUE THREAD

**Issue by mdhornet90** [covidsafe/App-Android#35]
https://github.com/covidsafe/App-Android/blob/10dcb0f3c208e8bc4993682ae8e7e75a7cdab698/app/src/main/java/edu/uw/covidsafe/utils/Constants.java#L64

**Comment by justinklchan** [comment]
Yes, the app is still under active development. An eventual full public release (i.e. *not* a demo) would require full integration with the public health authorities of particular states.

But before that time, it is easier to do testing with DEBUG turned on.

Our Wiki has an explanation of this flag and what it does.
https://github.com/covidsafe/App-Android/wiki/Running-the-app
