### ISSUE TITLE
strings.xml for Spanish

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-Android#36]
1) Make sure all strings throughout the code is merged into strings.xml.
2) Organize strings.xml
3) Translate into Spanish
4) Have an option in the Settings to toggle between the languages

**Comment by aakash1313** [comment]
@justinklchan 
Update: All the UI strings are now in strings.xml

**Comment by justinklchan** [comment]
There's still strings in the Java text for example TipRecyclerViewAdapter which populates the recycler view with various text. You'll probably have to scrub through all the Java code.

**Comment by aakash1313** [comment]
@justinklchan : yes, next step is that :)

**Comment by bananateg** [comment]
Hi I am working at this moment, putting values-es

**Comment by justinklchan** [comment]
Great, thank you @bananateg if you would like other issues to work on, can you email me at jucha@cs.washington.edu? I can add you to our Slack and discuss some bigger features and other things we need help on for this project. Thank you so much for offering your help.

**Comment by bananateg** [comment]
![Screenshot_1588000352](https://user-images.githubusercontent.com/1156640/80388579-accbb480-886f-11ea-8137-955257395248.png)

**Comment by bananateg** [comment]
I created a local branch.
I put only example Language part
At image is how show

**Comment by aakash1313** [comment]
@bananateg : Hey thanks for taking this up, just wanted to make sure that we are following the best practices while working on this:
1. Changing the locale of the app should not change the device locale.
2. Restarting the app after changing the locale is not a good UX and can lead to anomaly in the behavior, please make sure that we don't do that.
3. After changing the locale, make sure everything is aligned as per the locale and tested properly. 4. Please make sure that activity/fragment titles respect the locales too.
5. Please feel free to ping @justinklchan  or me  if you need any help while working on this.

**Comment by justinklchan** [comment]
@aakash1313 @bananateg Make the look of this feature adheres to our designs
<img width="216" alt="Screen Shot 2020-04-27 at 1 28 55 PM" src="https://user-images.githubusercontent.com/174899/80417754-1c9b6880-888b-11ea-90e5-b2926abd3d28.png">

**Comment by bananateg** [comment]
Press Language I need to open a dialog for select at language?

**Comment by justinklchan** [comment]
@bananateg for now just have it as a drop down, we don't need a dialog

**Comment by justinklchan** [comment]
@aakash1313 
I went through every file manually and moved the remaining strings into the XML file.
Can you get the remaining strings I've pulled over translated into Spanish?
After that mark this issue as closed.

We don't need an option in the settings.

I realized if you change the language in the System Settings of Android, it switches the language automatically, so we don't need this option in our own app.

**Comment by aakash1313** [comment]
@justinklchan : Awesome, thanks justin, yes that is how localization works if you add more strings to it, it will automatically pick up the device locale and do it for you. Will change the remaining strings and close it today :)

**Comment by bananateg** [comment]
I finish the change of language, the user only change te language into te app, te language 
of device no need change,

**Comment by aakash1313** [comment]
@justinklchan : Added the remaining strings, 
@bananateg : I agree with you, can you please add that change?

**Comment by bananateg** [comment]
@aakash1313 yes, i need to create another local branch or is posible that agregate by create 
the branch remote

**Comment by justinklchan** [comment]
Whichever is easier for you. We can merge it when you have the code pushed.

**Comment by bananateg** [comment]
@justinklchan done, who send my code

**Comment by aakash1313** [comment]
@bananateg : Can you create a PR out of it and add @justinklchan as an approver?
