### ISSUE TITLE
Add multiple phone contacts at once

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-Android#47]
Currently you can only add phone contacts one at a time. 

Allow user to add multiple contacts at once. 

Best way to do this is to create an empty project of your own with code to do this.
Then integrate that code into this project.
Then make the pull request.

You should be able to log the contact's name, phone number, and URI to their avatar.

**Comment by bananateg** [comment]
@chanjustin i send a email please check

**Comment by justinklchan** [comment]
@bananateg didn't get an email, what did it say?
I merged your feature where you used a third party library into the main branch for now.
But if you found a way to do this with native library, we can replace the code.

**Comment by bananateg** [comment]
@justinklchan  plaese check this  
[MyContacts.zip](https://github.com/covidsafe/App-Android/files/4574992/MyContacts.zip)

**Comment by justinklchan** [comment]
@bananateg thanks for doing this, I tried out the app. However I think your solution using the third party library is better, and I have merged that into the main repository.
