### ISSUE TITLE
android.app.ActivityThread$H.handleMessage

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-Android#49]
ActivityThread.java, line 1893
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8ccfc69 u0 edu.uw.covidsafe/.LoggingService}

Thought this was fixed, but maybe it was not.

This happened on a phone with API 9.

If this issue is related to API version, then #50 will deal with this also.

**Comment by justinklchan** [comment]
@aakash1313 verify that this is an issue with using a low API version.
If that is the issue, close the issue.
We fix that by just doing an API version check at the start and alerting users if their API version is too low.

**Comment by aakash1313** [comment]
@aakash1313 : Going through the google issue tracker it seems to be a known issue and google has not released a permanent fix for it. There are workarounds available but they will not eliminate it completely.  Looking for some other alternatives.

**Comment by aakash1313** [comment]
@justinklchan : can you confirm if it is fixed in the latest code?

**Comment by justinklchan** [comment]
It's hard to say because it doesn't crash deterministically. And these crashes haven't happened on my own device. I'll close this for now. And reopen if it arises again.
