### ISSUE TITLE
Logging Service does not work after device restart

### ISSUE THREAD

**Issue by aakash1313** [covidsafe/App-Android#55]

**Comment by justinklchan** [comment]
Just to be clear about this:
If you close the *app* and open it again, the logging service restarts.
And if you close the *device* and restart it, the logging service does not restart.

How can we expect to resolve this? With any other service like a music service or a web server, if you restart the device, there is no way to automatically restart the service until you open the app again. Can you clarify?

**Comment by aakash1313** [comment]
@justinklchan : Right, firstly after going through the android intent service doc there are certain things I noticed: 
1. Our use case is not suitable for using an intentservice, IntentService is generally used for scenarios where we want the system to perform a background task for us and finishes it when that completes. We don't control the lifecycle of it. It will stop itself once the job is over. While in our case, we want to have control over starting or stopping a service.
2. As per the doc, we should not override onStartCommand() while in the code i noticed we are doing it.
3. IntentService is deprecated and for the kind of usecases mentioned in above points we should use JobIntentService or WorkManager if the job is deferrable and guaranteed. This is not the case for us so we can't use JobIntentService. 
3. Now the only solution left for us is using a BoundService, which is applicable for this use case, it will help us maintaining the IPC (i.e when to start or stop).
4. @justinklchan , the question how we can resolve this , is by using the system broadcasts (BOOT_COMPLETED) and start a foreground service when we listen to that. 
5. Making the user manually start the app is not a good UX in my understanding and we should handle it using broadcast receivers.
Do let me know what you think about it?

**Comment by justinklchan** [comment]
I agree with you. Replace IntentService with the BoundService and listen for BOOT_COMPLETED.

**Comment by aakash1313** [comment]
@justinklchan : can you pull the latest and test if it works for you ? Added the auto restart service logic as well. :)

**Comment by justinklchan** [comment]
@aakash1313 this is great
It seems there is some waiting period after the boot until it happens (did not know this and at first thought it was broken).

I followed a few other tips here, check out my commit to see if you agree:
https://stackoverflow.com/questions/20441308/boot-completed-not-working-android

Great that you already opened an issue to do the same for the PullService. It should basically be the same work.

Good job for this issue!

**Comment by aakash1313** [comment]
oops, i didn't we have that intent flag as well. thanks @justinklchan  :)
