### ISSUE TITLE
Pull Service to be moved to Work Manager instead of Intent Service

### ISSUE THREAD

**Issue by aakash1313** [covidsafe/App-Android#58]

**Comment by aakash1313** [comment]
@justinklchan : Do we want this service to be always running in background?

**Comment by justinklchan** [comment]
The Service encapsulates two tasks:
The PullFromServerTask which runs once an hour
The LogPurgerTask which runs once a day

I am guessing you need a service constantly running for this to happen.
But if you know of other ways to do this that is less power hungry, please post them.

**Comment by aakash1313** [comment]
@justinklchan : I think it seems to be a deferrable task, how about if we let work manager perform it for us.  It will take care of the battery constraints and we can add retry logic to it, if we fail. 
Since it doesn't require to be run continuously (like location logging ), as a best practice for background process, work manager will handle it efficiently for us.

Let me know what you think about it?

![image](https://user-images.githubusercontent.com/3194646/80302475-245dee80-875f-11ea-8f1d-0d4389871595.png)

**Comment by justinklchan** [comment]
This seems good, just read a little about WorkManager. As long as you can set the constraint to run at particular time intervals (doesn't have to be exact), that is fine.
For example for the Pull task we can check for network connectivity.
And also check for low battery for both tasks.

**Comment by aakash1313** [comment]
@justinklchan : This is done, should we close this?

**Comment by justinklchan** [comment]
let me verify
