### ISSUE TITLE
MaterialCalendarView crash

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-Android#59]
API it occurred on: 6.0.1

Possibility related to low API.

com.prolificinteractive.materialcalendarview.CalendarDay.toString
CalendarDay.java, line 153

java.lang.IntegralToString.convertInt IntegralToString.java:216
java.lang.IntegralToString.appendInt IntegralToString.java:173
java.lang.StringBuilder.append StringBuilder.java:139
**com.prolificinteractive.materialcalendarview.CalendarDay.toString CalendarDay.java:153**
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:125**
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127**
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127**
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127**
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174**
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174**
**edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127**
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:174
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:127
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setRangeDates CalendarPagerAdapter.java:284
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setRangeDates WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setRangeDates MaterialCalendarView.java:1135
com.prolificinteractive.materialcalendarview.MaterialCalendarView.commit MaterialCalendarView.java:1988
com.prolificinteractive.materialcalendarview.MaterialCalendarView.access$2200 MaterialCalendarView.java:69
com.prolificinteractive.materialcalendarview.MaterialCalendarView$StateBuilder.commit MaterialCalendarView.java:1922
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onRestoreInstanceState MaterialCalendarView.java:1109
android.view.View.dispatchRestoreInstanceState View.java:14764
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchRestoreInstanceState MaterialCalendarView.java:1130
android.view.ViewGroup.dispatchRestoreInstanceState ViewGroup.java:3178
androidx.fragment.app.Fragment.restoreViewState Fragment.java:573
androidx.fragment.app.FragmentStateManager.restoreViewState FragmentStateManager.java:346
androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1187
androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1354
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState FragmentManager.java:1432
androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1495
androidx.fragment.app.BackStackRecord.executeOps BackStackRecord.java:447
androidx.fragment.app.FragmentManager.executeOps FragmentManager.java:2167
androidx.fragment.app.FragmentManager.executeOpsTogether FragmentManager.java:1990
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute FragmentManager.java:1945
androidx.fragment.app.FragmentManager.execSingleAction FragmentManager.java:1816
androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss BackStackRecord.java:303
androidx.fragment.app.FragmentPagerAdapter.finishUpdate FragmentPagerAdapter.java:238
androidx.viewpager.widget.ViewPager.populate ViewPager.java:1244
androidx.viewpager.widget.ViewPager.populate ViewPager.java:1092
androidx.viewpager.widget.ViewPager.onMeasure ViewPager.java:1622
android.view.View.measure View.java:18805
androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren ConstraintLayout.java:1227
androidx.constraintlayout.widget.ConstraintLayout.onMeasure ConstraintLayout.java:1572
android.view.View.measure View.java:18805
androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren ConstraintLayout.java:1227
androidx.constraintlayout.widget.ConstraintLayout.onMeasure ConstraintLayout.java:1572
android.view.View.measure View.java:18805
androidx.appcompat.widget.ContentFrameLayout.onMeasure ContentFrameLayout.java:143
android.view.View.measure View.java:18805
androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure ActionBarOverlayLayout.java:403
android.view.View.measure View.java:18805

**Comment by aakash1313** [comment]
@justinklchan : The crash doesn't seem to be clear from this . Are these  the complete logs?

**Comment by justinklchan** [comment]
Yes, check out the AppCenter crash. 
There is no particular reason, and it may have to be replaced. We need a month view calendar where we can support dots to mark dates where a user has a valid symptom record or location record. #40
