### ISSUE TITLE
java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-Android#68]
We need to change our calendar, this custom one is causing us various issues.

edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:126
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setDateSelected CalendarPagerAdapter.java:307
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setDateSelected WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setDateSelected MaterialCalendarView.java:826
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setSelectedDate MaterialCalendarView.java:814
edu.uw.covidsafe.symptoms.SymptomTrackerFragment.updateFeaturedDate SymptomTrackerFragment.java:173
edu.uw.covidsafe.symptoms.SymptomTrackerFragment$2.onDateSelected SymptomTrackerFragment.java:128
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchOnDateSelected MaterialCalendarView.java:1364
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onDateUnselected MaterialCalendarView.java:1500
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.validateSelectedDates CalendarPagerAdapter.java:356
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.invalidateSelectedDates CalendarPagerAdapter.java:343
com.prolificinteractive.materialcalendarview.CalendarPagerAdapter.setRangeDates CalendarPagerAdapter.java:284
com.prolificinteractive.materialcalendarview.WeekPagerAdapter.setRangeDates WeekPagerAdapter.java:9
com.prolificinteractive.materialcalendarview.MaterialCalendarView.setRangeDates MaterialCalendarView.java:1135
com.prolificinteractive.materialcalendarview.MaterialCalendarView.commit MaterialCalendarView.java:1988
com.prolificinteractive.materialcalendarview.MaterialCalendarView.access$2200 MaterialCalendarView.java:69
com.prolificinteractive.materialcalendarview.MaterialCalendarView$StateBuilder.commit MaterialCalendarView.java:1922
com.prolificinteractive.materialcalendarview.MaterialCalendarView.onRestoreInstanceState MaterialCalendarView.java:1109
android.view.View.dispatchRestoreInstanceState View.java:20262
com.prolificinteractive.materialcalendarview.MaterialCalendarView.dispatchRestoreInstanceState MaterialCalendarView.java:1130
android.view.ViewGroup.dispatchRestoreInstanceState ViewGroup.java:4045
androidx.fragment.app.Fragment.restoreViewState Fragment.java:573
androidx.fragment.app.FragmentStateManager.restoreViewState FragmentStateManager.java:346
androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1187
androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1354
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState FragmentManager.java:1432
androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1495
androidx.fragment.app.BackStackRecord.executeOps BackStackRecord.java:447
androidx.fragment.app.FragmentManager.executeOps FragmentManager.java:2167
androidx.fragment.app.FragmentManager.executeOpsTogether FragmentManager.java:1990
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute FragmentManager.java:1945
androidx.fragment.app.FragmentManager.execSingleAction FragmentManager.java:1816
androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss BackStackRecord.java:303
androidx.fragment.app.FragmentPagerAdapter.finishUpdate FragmentPagerAdapter.java:238
androidx.viewpager.widget.ViewPager.populate ViewPager.java:1244
androidx.viewpager.widget.ViewPager.populate ViewPager.java:1092
androidx.viewpager.widget.ViewPager.onMeasure ViewPager.java:1622
android.view.View.measure View.java:24953
androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren ConstraintLayout.java:1227
androidx.constraintlayout.widget.ConstraintLayout.onMeasure ConstraintLayout.java:1572
android.view.View.measure View.java:24953
androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren ConstraintLayout.java:1227
androidx.constraintlayout.widget.ConstraintLayout.onMeasure ConstraintLayout.java:1572
android.view.View.measure View.java:24953
androidx.appcompat.widget.ContentFrameLayout.onMeasure ContentFrameLayout.java:143
android.view.View.measure View.java:24953
androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure ActionBarOverlayLayout.java:403
android.view.View.measure View.java:24953

**Comment by bananateg** [comment]
I am testing the calendar and do not have problem with calendar (exterm)

**Comment by justinklchan** [comment]
@bananateg i don't have a problem on my phone too. but we are getting many many problems with the calendar from our beta users. we are doing crash logging, and we can see lots of different crashes. so we have to replace it.

**Comment by bananateg** [comment]
Ok the calendarview of android do not have the possibility show only a one week, i need to replace the component with another that offer that

**Comment by justinklchan** [comment]
@bananateg please comment here your findings before implementing it.
i will look into this deeper later. maybe if we can mitigate the crashes we can continue using that calendar, but i doubt it. the crashes are seeming to come from other parts of their library also.

**Comment by bananateg** [comment]
@justinklchan i view this link that has many calendar library https://medium.com/@Patel_Prashant_/android-custom-calendar-with-events-fa48dfca8257

If you have another information by issue is how version android and hardware of device

**Comment by justinklchan** [comment]
@aakash1313 let's do this feature in a separate branch.
the calendar is very intertwined with various components and i don't want the main branch to break as we transition to the new calendar.

**Comment by justinklchan** [comment]
@aakash1313 this is possibly fixed with @3ad19ced6b4c6dc0703775931d9546d6da88f43f

If you inspect the logs carefully and go through the actual code in the library it seems
 that the setSelectedDate() method is passed a date outside the minDate and maxDate range (defined as the 14 day infection window)

The library tries to validate this, and fails, so it tries to unselect this invalid date. Which triggers our onDateSelected listener.

**Comment by aakash1313** [comment]
@justinklchan : If this is fixed, can we close this one ?
